### ISSUE TITLE
make gives error In toplevel form: g-utils.el:59:1:Error: Cannot open load file: json make: *** [g-utils.elc] Error 1

### ISSUE THREAD

**Issue by markmark1** [jaalto/emacs-epackage--g-client#2]
In toplevel form:
g-utils.el:59:1:Error: Cannot open load file: json
make: *** [g-utils.elc] Error 1

**Comment by jaalto** [comment]
g-cal requires latest Emacs 25.x which includes json. G-cal also requires full installation of official org-mode from https://github.com/tomprince/org-mode - Unfortunately the org-mode included in Emacs does not yet include org-exp.el which g-cal requires,
